### ISSUE TITLE
What is the license of the project

### ISSUE THREAD

**Issue by sagarsahu27** [nnsuite/meta-neural-network#40]
I need to use this project and but I see LICENSE is missing, can you add license to this project ?

**Comment by myungjoo** [comment]
This is a meta for a set of packages. Thus, what really matters is the licenses of the packages "directed" by the meta.

@wooksong I propose to use Apache-2.0 for this meta itself. Please make it clear (somewhere in README or LICENSE itself) that the license of this meta CANNOT dictate the licenses of packages directed by this meta.

**Comment by wooksong** [comment]
> This is a meta for a set of packages. Thus, what really matters is the licenses of the packages "directed" by the meta. For example, "nnstreamer" in this meta is LGPL-2.1 and "tensorflow" in this meta is basically Apache-2.0 (some subcomponents of it might have difference licenses)
> 
> @wooksong I propose to use Apache-2.0 for this meta itself. Please make it clear (somewhere in README or LICENSE itself) that the license of this meta CANNOT dictate the licenses of packages directed by this meta.

Acked

**Comment by myungjoo** [comment]
@sagarsahu27 It is now officially Apache 2.0.

**Comment by sagarsahu27** [comment]
Thanks for the information, I tried nnstreamer with tflite 1.14 and its working flawless. Didn't check the delegate part yet. I am still new to gstreamer but your project is really helpful to those who want to kickstart ML with gstreamer. Really appreciate your efforts.
